version: '3.1'

services:
  database:
    image: postgres:9.6
    environment: 
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    secrets:
      - db_pass
    volumes:
      - drupal-data:/var/lib/postgresql/data

  drupal:
    image: drupal:8.5.3
    volumes: 
       - drupal-modules:/var/www/html/modules
       - drupal-profiles:/var/www/html/profiles
       - drupal-themes:/var/www/html/themes
       - drupal-sites:/var/www/html/sites
    ports:
      - 8080:80
volumes: 
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data:
  
secrets:
  db_pass:
    external: true